# Generated by Django 3.2 on 2021-04-26 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Title')),
                ('blog_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('blog_desc', models.TextField(max_length=20000, verbose_name='Description')),
                ('blog_pubdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published Date & Time')),
                ('blog_publish', models.BooleanField(verbose_name='Publish Status')),
                ('blog_img', models.ImageField(upload_to='blogimages/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
