# Generated by Django 3.2 on 2021-04-26 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210426_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_pubdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Published Date & Time'),
        ),
    ]
