# Generated by Django 3.2 on 2021-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtoSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(verbose_name='Appointment id')),
                ('patient', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Patient to Staff Notification',
            },
        ),
        migrations.AlterField(
            model_name='appointments',
            name='a_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date And Time'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='d_prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Doctor Prescription'),
        ),
    ]
