# Generated by Django 3.2 on 2021-04-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210428_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoPNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(verbose_name='Appointment id')),
                ('patient', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Staff to Patient Notification',
            },
        ),
    ]
