# Generated by Django 3.2 on 2021-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_stopnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoDNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(verbose_name='Appointment id')),
                ('doctor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Staff to Doctor Notification',
            },
        ),
    ]
