# Generated by Django 3.2 on 2021-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_stodnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtoPNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(verbose_name='Appointment id')),
                ('doctor', models.CharField(max_length=255)),
                ('patient', models.CharField(max_length=255)),
                ('meeting_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Doctor to Patient Notification',
            },
        ),
    ]
