# Generated by Django 4.0 on 2022-04-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_dtopnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='productsimages/')),
                ('product_title', models.CharField(max_length=30, unique=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_desc', models.TextField()),
                ('product_count', models.CharField(max_length=10)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(upload_to='productsimages/', verbose_name='Image')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.products', verbose_name='Product Title')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
