# Generated by Django 4.0 on 2022-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
